routes/page_routes.py
from flask import Blueprint, render_template, abort, session, redirect, url_for, request
from functools import wraps
from lib.Functions import Functions
from time import time

from nav import navigation_bar

def requires_auth(f):
	@wraps(f)
	def decorated_auth(*args, **kwargs):
		if functions.isVerified():
			functions.getUserInfo()
		else:
			return redirect(url_for('page_routes.login', secure_uri=functions.getAuthURI()))
		return f(*args, **kwargs)
	return decorated_auth

def requires_admin(f):
	@wraps(f)
	def decoracted_admin(*args, **kwargs):
		if not functions.isAdmin():
			return redirect(url_for('page_routes.index'))
		return f(*args, **kwargs)
	return decoracted_admin

page_routes = Blueprint('page_routes', __name__, template_folder='templates')

functions = Functions()

#Main routes
@page_routes.route('/')
@requires_auth
def index():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'index.html',
		title="Dashboard",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/assets')
@requires_auth
@requires_admin
def assets():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'corpassets.html',
		title="Corp Assets",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/pricing')
@requires_auth
def pricing():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'pricing.html',
		title="Pricing Lookup",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/mining')
@requires_auth
def mining():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'mining.html',
		title="Mining",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/contracts')
@requires_auth
def contracts():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'contracts.html',
		title="Contracts",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/production')
@requires_auth
def production():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'production.html',
		title="Production",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/structures')
@requires_auth
def structures():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'structures.html',
		title="Structures",
		notification=notification,
		navigation_bar=navigation_bar,
		ts=str(int(time()))
		)

@page_routes.route('/login', methods=["GET","POST"])
def login():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	if functions.isLoggedIn():
		return redirect(url_for('page_routes.index'))
	if request.method == "POST":
		res = functions.loginUser(request.form)
		if not res:
			return redirect(url_for('page_routes.index'))
	return render_template(
		'login.html',
		title='Login',
		notification=notification,
		navigation_bar=navigation_bar,
		secure_uri=request.args["secure_uri"],
		ts=str(int(time()))
		),401

@page_routes.route('/oauth')
def oauth():
	functions.checkInUser(request.args.get('code'))
	return redirect(url_for('page_routes.index'))

@page_routes.route('/logout')
@requires_auth
def logout():
	functions.logoutUser()
	return redirect(url_for('page_routes.login', secure_uri=functions.getAuthURI()))

@page_routes.route('/admin')
@requires_auth
@requires_admin
def admin():
	notification = {}
	if "notification" in session:
		notification = {
			"message": session["notification"],
			"type": session["notificationtype"]
		}
		session.pop("notification")
		session.pop("notificationtype")
	return render_template(
		'admin.html',
		title="Admin page",
		navigation_bar=navigation_bar,
		notification=notification,
		ts=str(int(time()))
		)

templates/admin.html
{% extends 'layout.html' %} 
{% block body %}
<script src="{{ url_for('static', filename='js/admin.js', version=ts) }}"></script>
<section class="content-header">
    <h1>Admin page</h1>
    <ul class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Administration</li>
    </ul>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Users</h3>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover" id="userTable">
                        <thead>
                            <tr>
                                <th>Character</th>
                                <th>Group</th>
                                <th>LastSeen</th>
                                <th>Options</th>
                            </tr>
                        </thead>
                        <tbody class="userList">
                        </tbody>
                    </table>
                </div>
                <div class="box-footer clearfix">
                    <a href="" data-toggle="modal" data-target="#addUserModal" class="btn btn-sm btn-info btn-pull-left">Add User</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% include 'modals/editUserModalAdmin.html' %}

templates/contracts.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/contracts.js', version=ts) }}"></script>
<section class="content-header">
	<h1>Corp Contracts</h1>
	<ul class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Corp Contracts</li>
	</ul>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Corp Contracts</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover" id="assetsTable">
						<thead>
							<tr>
								<th>Item</th>
								<th>Location</th>
								<th>Quantity</th>
								<th>Other</th>
								<th>Marketgroup</th>
							</tr>
						</thead>
						<tbody class="assetsList">
						</tbody>
					</table>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/corpassets.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/corpassets.js', version=ts) }}"></script>
<section class="content-header">
	<h1>Corp Assets</h1>
	<ul class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Corp Assets</li>
	</ul>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Corp assets</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover" id="assetsTable">
						<thead>
							<tr>
								<th>Item</th>
								<th>Location</th>
								<th>Quantity</th>
								<th>Other</th>
								<th>Marketgroup</th>
							</tr>
						</thead>
						<tbody class="assetsList">
						</tbody>
					</table>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/index.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/dashboard.js', version=ts) }}"></script>
<section class="content-header">
	<h1>Dashboard</h1>
	<ul class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ul>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Industry Jobs</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<div class='nav-tabs-custom'>
						<ul class="nav nav-tabs">
							<li class='active'>
								<a href="#manu" data-toggle="tab" aria-expanded="true">Manufacturing</a>
							</li>
							<li>
								<a href="#copy" data-toggle="tab" aria-expanded="false">Copying</a>
							</li>
							<li>
								<a href="#res" data-toggle="tab" aria-expanded="false">Research</a>
							</li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="manu">
								<table class="table table-hover" id="industryManuTable">
									<thead>
										<tr>
											<th>Item</th>
											<th>Character</th>
											<th>Location</th>
											<th>Action</th>
											<th>Start</th>
											<th>End</th>
											<th>Timeleft</th>
										</tr>
									</thead>
									<tbody class="industryManuList">
									</tbody>
								</table>
							</div>
							<div class="tab-pane" id="copy">
								<table class="table table-hover" id="industryCopyTable">
									<thead>
										<tr>
											<th>Item</th>
											<th>Character</th>
											<th>Location</th>
											<th>Action</th>
											<th>Start</th>
											<th>End</th>
											<th>Timeleft</th>
										</tr>
									</thead>
									<tbody class="industryCopyList">
									</tbody>
								</table>
							</div>
							<div class="tab-pane" id="res">
								<table class="table table-hover" id="industryResTable">
									<thead>
										<tr>
											<th>Item</th>
											<th>Character</th>
											<th>Location</th>
											<th>Action</th>
											<th>Start</th>
											<th>End</th>
											<th>Timeleft</th>
										</tr>
									</thead>
									<tbody class="industryResList">
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>

<head>
	<title> LOCKR | {{ title }}</title>

	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">	

	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
	<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/ionicons.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/AdminLTE.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/_all-skins.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/alertify.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/highcharts.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/select2.css') }}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">

	<!-- <script src="{{ url_for('static', filename='js/vendor/jquery.min.js') }}"></script> -->
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="{{ url_for('static', filename='js/vendor/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/alertify.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/jquery.dataTables.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/dataTables.bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/moment.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/select2.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/datatable.moment.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/adminlte.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/highcharts.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/vendor/jquery-ui.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/custom.js') }}"></script>
</head>

<body class="skin-green sidebar-mini {% if session.token is not defined %} sidebar-collapse {% endif %}">
	<div class="wrapper">
		<header class="main-header">
			<a href="/" class="logo">
				<span class="logo-mini"><b>L</b>KR</span>
				<span class="logo-lg"><b>L</b>OCKR</span>
			</a>

			{% if session.token%}
			<nav class="navbar navbar-static-top">
				<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle Navigation</span>
				</a>

				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<li>
							<a class="refresh" href="#"><span class="fa fa-refresh" id="refreshSpinner"></span></a>
						</li>
						<li>
							<a class="logoutButton" href="{{ url_for('page_routes.logout') }}">Logout</a>
						</li>
					</ul>
				</div>
			</nav>
			{% endif %}
		</header>
		<aside class="main-sidebar">
			<section class="sidebar">
				<div class="user-panel">
					{% if session.token %}
						<div class="pull-left image">
								<img class="img-circle" src="https://image.eveonline.com/Character/{{session.char.CharacterID}}_64.jpg">
						</div>
						<div class="pull-right info">
							<p>{{ session.char.CharacterName }}</p>
							<i class="fa fa-circle text-success"></i>{{ session.curLoc }}
						</div>
					{% else %}
						<div class="pull-left image">
								<img class="img-circle" src="{{ url_for('static', filename='img/LogoFull.png') }}">
						</div>
					{% endif %}
				</div>
				<ul class="sidebar-menu">
					{% if session.token %}
						<li class="header">MAIN NAVIGATION</li>
						{% for href, id, logo, caption, hasAdmin in navigation_bar %}
							{% if hasAdmin and session.isAdmin %}
								<li>
									<a href="{{ href|e }}">
										<i class="{{ logo|e }}"></i> <span>{{ caption|e }}</span>
									</a>
								</li>
							{% elif not hasAdmin %}
								<li>
									<a href="{{ href|e }}">
										<i class="{{ logo|e }}"></i> <span>{{ caption|e }}</span>
									</a>
								</li>
							{% endif %}
						{% endfor %}
					{% endif %}
				</ul>
			</section>
		</aside>
		<div class="content-wrapper">{{ active_page }}
            {% block body %}{% endblock %}
        </div>

        {% if notification %}
        <script>
        	alertify.{{notification.type}}("{{ notification.message }}");
        </script>
        {% endif %}

        <footer class="main-footer">
        	<div class="pull-right hidden-xs">
        		<b>Version</b> 0.1.0
        	</div>
        	<strong>
        		<a href="https://lockr.madpilot.nl" target="_blank">LOCKR</a>
        	</strong>
        </footer>
	</div>
</body>

</html>

templates/login.html
{% extends 'layout.html' %} 
{% block body %}
<section class="content">
	<div class="container login-container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<img src="https://image.eveonline.com/Corporation/98103378_256.png" width=400px>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 loginform">
				<h2>Login</h2>
				<a href="{{secure_uri}}"><img src='https://images.contentful.com/idjq7aai9ylm/4fSjj56uD6CYwYyus4KmES/4f6385c91e6de56274d99496e6adebab/EVE_SSO_Login_Buttons_Large_Black.png?w=270&h=45'></a>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/mining.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/mining.js', version=ts) }}"></script>
<section class="content-header">
	<h1>Corp Mining</h1>
	<ul class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Corp Mining</li>
	</ul>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Corp Mining</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover" id="assetsTable">
						<thead>
							<tr>
								<th>Item</th>
								<th>Location</th>
								<th>Quantity</th>
								<th>Other</th>
								<th>Marketgroup</th>
							</tr>
						</thead>
						<tbody class="assetsList">
						</tbody>
					</table>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/pricing.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/pricing.js', version=ts) }}"></script>
<section class="content-header">
    <h1>Pricing and Minerals lookup</h1>
    <ul class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Pricing</li>
    </ul>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/34_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Tritanium
                    </div>
                    <div class="info-box-number tritIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/35_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Pyerite
                    </div>
                    <div class="info-box-number pyeIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/36_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Mexallon
                    </div>
                    <div class="info-box-number mexIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/37_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Isogen
                    </div>
                    <div class="info-box-number isoIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/38_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Nocxium
                    </div>
                    <div class="info-box-number nocxIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/39_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Zydrine
                    </div>
                    <div class="info-box-number zydIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
                <span class="info-box-icon bg-green">
					<img src='https://image.eveonline.com/Type/40_64.png'>
				</span>
                <div class="info-box-content">
                    <div class="info-box-text">
                        Megacyte
                    </div>
                    <div class="info-box-number megaIsk">0</div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="info-box">
				<span class="info-box-icon bg-green" style="cursor:pointer" onclick='updatePrices()'>
					<i class="fa fa-refresh" id="spinRefresh"></i>
				</span>
				<div class="info-box-content">
					<div class="info-box-text">
						Pricing
					</div>
					<div class="info-box-number totalIsk">Reload</div>
				</div>
			</div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Price info</h3>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover" id="priceTable">
                        <thead>
                            <tr>
                                <th>Item</th>
                                <th>Buy Price</th>
                                <th>Build Price</th>
                                <th>Options</th>
                            </tr>
                        </thead>
                        <tbody class="priceList">
                        </tbody>
                    </table>
                </div>
                <div class="box-footer clearfix">
                	<select class="form-control" multiple="multiple" name="itemList" id="itemList">

                    </select>
                	<button class="btn btn-info" onclick='postItems()'>Add Item</button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/production.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/production.js', version=ts) }}"></script>
<section class="content-header">
	<h1>Production</h1>
	<ul class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Production</li>
	</ul>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Production</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover" id="productionTable">
						<thead>
							<tr>
								<th width='70px'>Planned</th>
								<th width='100px'>Item</th>
								<th>Materials</th>
							</tr>
						</thead>
						<tbody class="productionList">
						</tbody>
					</table>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Production parts</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover" id="partsTable">
						<thead>
							<tr>
								<th width='100px'>Item</th>
								<th>In stock</th>
								<th>In build</th>
								<th>Required</th>
								<th>Need to build</th>
							</tr>
						</thead>
						<tbody class="partsList">
						</tbody>
					</table>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/structures.html
{% extends 'layout.html' %} {% block body %}
<script src="{{ url_for('static', filename='js/structures.js', version=ts) }}"></script>
<section class="content-header">
	<h1>Structures</h1>
	<ul class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Structures</li>
	</ul>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Structures</h3>
				</div>
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover" id="assetsTable">
						<thead>
							<tr>
								<th>Item</th>
								<th>Location</th>
								<th>Quantity</th>
								<th>Other</th>
								<th>Marketgroup</th>
							</tr>
						</thead>
						<tbody class="assetsList">
						</tbody>
					</table>
				</div>
				<div class="box-footer clearfix">
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}